---
- name: Copy ioncube-loader ini into main extension config folder
  template:
    src: ioncube.ini.j2
    dest: "{{ item }}/{{ php_ioncube_loader_config_filename }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ php_extension_conf_paths }}"
  notify: "{{ handlers }}"
